### ISSUE TITLE
Import dxf from fusion, comes at 75% scale.

### ISSUE THREAD

**Issue by joebywan** [Jack000/Deepnest#110]
Importing a dxf into deepnest that was exported from fusion everything's importing at 75% the size it should be.  Fusion it looks fine, Qcad it looks fine, inkscape it looks fine.  Deepnest it doesn't.

**Comment by cmidgley** [comment]
Likely this question was too long ago to matter, but for anyone else looking - try [LaserPost for SVG](https://nucarve.com/laserpost-svg).  It's a Fusion post-processor that creates SVG) that I wrote for this very problem with Fusion and DXF (and projecting sketching, and ...!)  I've been using it with Deepnest with good results so far.
