### ISSUE TITLE
Feature Request: Part Spacing aka Offset

### ISSUE THREAD

**Issue by jophut** [Jack000/Deepnest#144]
Would it be possible to implement a part spacing or part offset feature?   
e.g. a CNC-router often uses an outer-contour method, then the mill diameter should be taken into account.   
Thus when using a 8mm mill, i'd like to use an offset of 10mm between individual parts.

**Comment by Krzewo** [comment]
That would be a nice feature to have...

**Comment by jophut** [comment]
Very sorry, totally missed the already existing input field!

![image](https://user-images.githubusercontent.com/3954707/162567710-12216e81-7629-4201-b654-db7328d93b42.png)
