### ISSUE TITLE
DXF loading improperly

### ISSUE THREAD

**Issue by Bjohnson131** [Jack000/Deepnest#148]
Hello, I have the following DXF as seen in Inventor TrueView:

![image](https://user-images.githubusercontent.com/1939015/176508439-3922bd10-1386-4cd5-bcb1-f1e715e1fed2.png)

and as seen in Deepnest: 

![image](https://user-images.githubusercontent.com/1939015/176509157-43af3d94-d45f-456e-a153-6368a2733fd3.png)

And in the nester UI:
![image](https://user-images.githubusercontent.com/1939015/176510323-37c2fdc6-d029-4485-884a-5310887e9068.png)

I've attached the DXF in question:
[W-1(2x-needed).zip](https://github.com/Jack000/Deepnest/files/9013156/W-1.2x-needed.zip)

**Comment by 9swampy** [comment]
Your DXF is invalid; check the outer edge is fully closed; no gaps. The break in what does get's loaded would be the first point to check:
![image](https://user-images.githubusercontent.com/523054/177022199-19a0db7f-2fc4-49a0-8f55-03f35958b4a2.png)

Note too that not all Dxf entities are likely to be supported. [This code](https://github.com/Jack000/Deepnest/blob/2fb10513a30681971dcc991c528fa0738a2c0c76/main/svgparser.js#L1106) might help you work out what you could try to limit yourself to; but the code linked is from the Svg parser after the remote service has done it's conversion of Dxf to Svg... and we don't have the code for that unfortunately.
