### ISSUE TITLE
Project maintained?

### ISSUE THREAD

**Issue by BenRoe** [Jack000/Deepnest#156]
The last commit was 4 years ago.
Is this project dead? If yes, does someone an alternative?

**Comment by cmidgley** [comment]
Look at issue #123 for a discussion on this topic.  @Jack000 appears to be no longer maintaining it, but several ports and forks have been made.  I've made a recent one at https://github.com/cmidgley/deepnest  which addresses just the basic problem of getting it to build again (using old Node/libraries).  It might be useful for minor changes and fixes, but IMHO the JavaScript code really needs a (time-consuming) refactoring to become truly viable long term.

**Comment by BenRoe** [comment]
Thank you for the information.
