### ISSUE TITLE
Help to build Deepnest app for window

### ISSUE THREAD

**Issue by vupqtran** [Jack000/Deepnest#4]
Hi @Jack000 ,
Can you share me how to build deepnest app for window?
I clone your source code and using npm to build but not success. It build complete but when run it can't start nest.
Thanks.

**Comment by huyhl248** [comment]
Hi @Jack000,
"the problem is the native addon", please give me more detail? I have same issue, no error when building. I can import, select object, 
![error0](https://user-images.githubusercontent.com/22191345/44640670-de43fc80-a977-11e8-8386-62da0ccf3c99.png)
but when I click on "Start nest", the software did not do anything.
![error](https://user-images.githubusercontent.com/22191345/44640669-de43fc80-a977-11e8-92eb-7058c9f0110c.png)
Please see the attached images.
Could you tell me what is the part of code that could effect? 
Thanks a lot!

**Comment by Jack000** [comment]
this means the c++ addon that's used to calculate the minkowski sum is not working

the addon is located in the minkowski directory. To see what the error is, unhide the web worker window ( show: true ) and open its developer tools - these configs are located in main.js

**Comment by huyhl248** [comment]
Hi @Jack000 ,
I followed your guide, unhide the web worker windows, open developer tools and uncomment this line in _main/index.html_
`var addon = require('../build/Release/addon');
`
But when I run with `npm run start`, this error appeared.
![error](https://user-images.githubusercontent.com/22191345/44835742-f622b700-abe9-11e8-8e6e-40ce23bcbc42.png)
I double-clicked to this error and it lead me to `var addon = require('../build/Release/addon');`
The attached files (remove ".txt") are what I configured, please help me!
[binding.gyp.txt](https://github.com/Jack000/Deepnest/files/2335008/binding.gyp.txt)
[main.js.txt](https://github.com/Jack000/Deepnest/files/2335009/main.js.txt)
[package.json.txt](https://github.com/Jack000/Deepnest/files/2335010/package.json.txt)
I built on **Windows 7 64 bit** and I want to use this app for this PC too.
Thanks.

**Comment by Jack000** [comment]
I think you need to build the addon on your local system. Try npm clean and npm build, then copy the files from ./build to ./minkowski

**Comment by Jack000** [comment]
try using this package.json for windows:

```
{
  "name": "Deepnest.io",
  "version": "1.0.5",
  "description": "Deep nesting for Laser and CNC",
  "main": "main.js",
  "scripts": {
    "start": "electron .",
    "configure": "node-gyp configure --release",
    "build": "node-gyp rebuild --target=1.4.8 --arch=ia32 --dist-url=https://atom.io/download/atom-shell",
    "clean": "node-gyp clean configure build --verbose --target=1.4.8 --arch=ia32 --dist-url=https://atom.io/download/atom-shell",
    "pack": "build --dir",
    "dist": "build --ia32",
    "postinstall": "npm i electron --arch=ia32 --save"
  },
  "repository": "https://github.com/Jack000",
  "keywords": [
    "Electron",
    "Nesting",
    "CNC",
    "Laser"
  ],
  "author": {
    "name": "Jack Qiao",
    "email": "jak000@gmail.com",
    "url": "http://deepnest.io"
  },
  "devDependencies": {
    "electron": "^1.4.8",
    "electron-builder": "^10.6.1",
    "electron-rebuild": "^1.8.2"
  },
  "dependencies": {
    "auth0-js": "^7.6.0",
    "auth0-lock": "^10.7.3",
    
    "electron-config": "^0.2.1",
    "electron-settings": "^2.2.2",
    "electron-window-manager": "^1.0.4",
    "filequeue": "^0.5.0",
    "graceful-fs": "^4.1.11",
    "melanke-watchjs": "^1.3.1",
    "nan": "^2.4.0",
    "paralleljs": "^0.2.1",
    "request": "^2.79.0",
    "write-file-queue": "0.0.1"
  },
  "build": {
    "appId": "com.deepnest.io",
    "copyright": "Copyright 2016 Jack Qiao",
    "compression": "maximum",
    "nodeGypRebuild": false,
    "mac": {
      "category": "public.app-category.utilities",
      "icon": "icon.icns"
    },
    "win": {
      "icon": "icon.ico"
    }
  }
}
```

**Comment by huyhl248** [comment]
Hi @Jack000 ,
I tried your suggestion, but the other error appeared:
![error0](https://user-images.githubusercontent.com/22191345/44889345-5832f900-ac8a-11e8-8115-a5a9ebc955e8.png)

I use **windows 7 64 bit**, and I want to run on the same machine.
Please help!
Thanks a lot!

**Comment by vupqtran** [comment]
Hi @Jack000 ,
Can you tell me your script to build deepnest source code using npm? 
ex:  
npm run configure
npm run build
....
Thanks.

**Comment by vupqtran** [comment]
Hi @Jack000 ,
I build successfully for **windows 7 64 bit**. But in your new content of package.json, i change this line:
**"postinstall": "npm i electron@1.4.8 --arch=ia32 --save-dev"**
and run postinstall before run install.
Thanks a lot.

**Comment by Jack000** [comment]
ok great, let me know if you have any other questions

**Comment by jisen96** [comment]
Hi @huyhl248 , I encountered the same problem as you. when I click on "Start nest", the software did not do anything.  What method did you use to solve it, could you tell me some details?  I also use windows 7 64 bit.
Thanks a lot.
