### ISSUE TITLE
Nesting does not use multiple sheets.

### ISSUE THREAD

**Issue by Danielaaroe** [Jack000/Deepnest#68]
It is indicated by the sheet-counter that nesting should be able to nest between multiple sheets. When my first sheet is full it does not create a sheet number 2, but keeps working without finishing a single version. Sheet is 2400mm*1200mm(full sheet) and components are up to 800mm diameter. GA population set to 5 to speed up first version of nest, but still nothing.

**Comment by ecridlebaugh** [comment]
Having this same issue

**Comment by vanThijs** [comment]
Deepnest doesn't do this automatically, but you can easily add another sheet: Mark you sheet as the sheet and increase the quantity to 2 or more. In my experience, deepnest will try to minimise the sheet use.

**Comment by Danielaaroe** [comment]
Unbelievable. I feel like an idiot. This issue is now solved. Thanks @vanThijs :)
