### ISSUE TITLE
Circles Turn into Polygons

### ISSUE THREAD

**Issue by bmalcheski** [Jack000/Deepnest#69]
It appears that small holes in parts are being segmented into lines making them into polygons rather than circles. We do not see this issue when directly importing the same files into our cutting software. This is not very noticeable to the eye but causes problems in our parts as the holes are then undersized.

**Comment by bmalcheski** [comment]
Found the curve tolerance setting.

**Comment by HASSSENE** [comment]
hey Bmalcheski how did you fix it?
