### ISSUE TITLE
[Feature Request] Command Line / API

### ISSUE THREAD

**Issue by mfussi** [Jack000/Deepnest#90]
Is it possible to adapt the application so that it is controllable over the command line? Or to add a simple API? I really would like to include this application in my automated build process. Currently I need to perform the nesting task by hand which is a bit cumbersome for many files.

Best Regards
Markus

**Comment by mfussi** [comment]
Implemented a simple REST API with my rudimentary Javascript skills, see here: https://github.com/mfussi/Deepnest/blob/master/main/webserver/webserver.js

Quick and dirty, no guarantees granted.

**Comment by Jumbo125** [comment]
not support dxf or?
